//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootCampQuiz.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BootCampQuiz.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to antwoord1;antwoord2;antwoord3;antwoord4;antwoord5
        ///antwoord6;antwoord7;antwoord8;antwoord9;antwoord10
        ///antwoord11;antwoord12;antwoord13;antwoord14;antwoord15
        ///antwoord16;antwoord17;antwoord18;antwoord19;antwoord20.
        /// </summary>
        internal static string antwoorden_finale {
            get {
                return ResourceManager.GetString("antwoorden_finale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AxInterop_ShockwaveFlashObjects {
            get {
                object obj = ResourceManager.GetObject("AxInterop_ShockwaveFlashObjects", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENRE 1
        ///GENRE 2
        ///GENRE 3.
        /// </summary>
        internal static string genres {
            get {
                return ResourceManager.GetString("genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Interop_ShockwaveFlashObjects {
            get {
                object obj = ResourceManager.GetObject("Interop_ShockwaveFlashObjects", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_boost {
            get {
                object obj = ResourceManager.GetObject("logo_boost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SharpDX {
            get {
                object obj = ResourceManager.GetObject("SharpDX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SharpDX_DirectInput {
            get {
                object obj = ResourceManager.GetObject("SharpDX_DirectInput", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;SharpDX.DirectInput&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:SharpDX.DirectInput.AssemblyDoc&quot;&gt;
        ///            &lt;summary&gt;
        ///            The &lt;see cref=&quot;A:SharpDX.DirectInput&quot;/&gt; assembly provides managed DirectInput API.
        ///            &lt;/summary&gt;
        ///            &lt;msdn-id&gt;ee416842&lt;/msdn-id&gt;
        ///            &lt;unmanaged&gt;DirectInput&lt;/unmanaged&gt;	
        ///            &lt;unmanaged-short&gt;DirectInput&lt;/unmanaged-short&gt;	
        ///        &lt;/member&gt;
        ///        &lt;member name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SharpDX_DirectInput1 {
            get {
                return ResourceManager.GetString("SharpDX_DirectInput1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;SharpDX&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:SharpDX.AssemblyDoc&quot;&gt;
        ///            &lt;summary&gt;
        ///            The &lt;see cref=&quot;N:SharpDX&quot;/&gt; assembly is the core assembly providing infrastructure for all managed DirectX API.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;T:SharpDX.CallbackBase&quot;&gt;
        ///            &lt;summary&gt;
        ///            Callback base implementation of &lt;see cref=&quot;T:SharpDX.ICallbackable&quot;/&gt;.
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SharpDX1 {
            get {
                return ResourceManager.GetString("SharpDX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Svt_Caspar {
            get {
                object obj = ResourceManager.GetObject("Svt_Caspar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Svt_Caspar_Controls {
            get {
                object obj = ResourceManager.GetObject("Svt_Caspar_Controls", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Svt_Network {
            get {
                object obj = ResourceManager.GetObject("Svt_Network", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Videohouse_Timing {
            get {
                object obj = ResourceManager.GetObject("Videohouse_Timing", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
